In [2]:
import numpy as np
import random

In [3]:
# Random value b/w 0 - given value
# single array
np.random.random(1)

array([0.64409858])

In [4]:
# Double random Tuple
np.random.random((3,3))

array([[0.42284169, 0.68630599, 0.69589138],
       [0.39198722, 0.41501429, 0.50823306],
       [0.68599315, 0.23005249, 0.61855189]])

In [7]:
# Double random Tuple Integer type value
np.random.randint((1,3))

array([0, 0])

In [9]:
# Double random Tuple Integer type array
np.random.randint(1,7,(6,6))

array([[1, 2, 2, 2, 2, 2],
       [2, 1, 1, 1, 2, 2],
       [1, 1, 1, 2, 1, 1],
       [2, 2, 1, 2, 2, 1],
       [1, 1, 1, 2, 1, 1],
       [1, 2, 2, 1, 1, 1]])

In [13]:
# random Tuple Integer type array N-D array {3}
np.random.randint(1,9,(3,6,6))

array([[[4, 6, 7, 8, 2, 1],
        [8, 2, 4, 4, 6, 8],
        [7, 5, 1, 4, 1, 4],
        [1, 5, 3, 2, 7, 7],
        [7, 4, 3, 7, 7, 6],
        [2, 5, 2, 8, 3, 1]],

       [[3, 1, 3, 2, 4, 3],
        [6, 4, 4, 3, 1, 6],
        [3, 8, 8, 7, 3, 6],
        [4, 7, 6, 8, 6, 7],
        [7, 7, 4, 7, 1, 3],
        [8, 2, 4, 4, 8, 2]],

       [[6, 3, 5, 7, 8, 5],
        [2, 5, 7, 4, 3, 8],
        [7, 7, 3, 3, 1, 1],
        [2, 7, 5, 6, 6, 4],
        [8, 2, 5, 1, 1, 6],
        [7, 7, 8, 6, 3, 5]]])

In [26]:
# Seed function size {(2**32)-1}
np.random.seed(50)
#(start, end, tuple(row and coloumn))
np.random.randint(1,9,(1,3,3))

array([[1, 1, 4],
       [6, 2, 7],
       [5, 7, 6]])

In [31]:
np.random.randint(1,9,(3,3))

array([[5, 4, 3],
       [5, 1, 4],
       [3, 3, 1]])

In [33]:
x = [4,7,8,3,5,9]
np.random.choice(x)

3

In [36]:
x = [4,7,8,3,5,9]
np.random.choice(x)

9