In [1]:
import numpy as np

In [4]:
# array(start, n-1 index) in 1 D
array_1 = np.arange(1,17)
print(array_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [5]:
# Using reshape function 2D format tuple(row,column)
array_1 = np.arange(1,17).reshape(4,4)
print(array_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
# Using reshape function 2D format tuple(row,column)
array_2 = np.arange(17,33).reshape(4,4)
print(array_2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [9]:
# " + " addition not for concatnate
array_1 + array_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [10]:
# Concatenate two matrix
np.concatenate((array_1,array_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [12]:
# Way of showing conaatente 
print(array_1)
print(array_2)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [20]:
#concatenate create tuple show by default 0 axis for columne
np.concatenate((array_1,array_2),axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [19]:
#concatenate create tuple show if row wise concatenate karna hai axis = 1
np.concatenate((array_1,array_2),axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [22]:
# Other way concatenate using vstack function for vertical( coloumn)
np.vstack((array_1,array_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [23]:
# Other way concatenate using hstack function for horizontal( row)
np.hstack((array_1,array_2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [28]:
# Split function - Break array
np.split(array_1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [27]:
print(array_1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
