# NumPY Function Matrics

In [1]:
import numpy as np

In [4]:
# np.arange(start, Ends(n-1), steps(gapping between))
array_1D = np.arange(1,13)
print(array_1D)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
differnce_array = np.arange(1,13,2)
print(differnce_array)

[ 1  3  5  7  9 11]


In [11]:
# np.linespace()
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [13]:
# Reshape convert
array_2D = array_1D.reshape(2,6)
print(array_2D)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
# arange function with reshape function = Matrix
array_arang_resh = np.arange(1,13).reshape(2,6)
print(array_arang_resh)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
#ravel function
array_arang_resh.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
#flatten()
array_arang_resh.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
# transpose()
array_arang_resh.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])