# Mathmatical Operation Using NumPy 03

In [1]:
import numpy as np

In [12]:
# mannul Way

array_01 = np.arange(1,10).reshape(3,3)
array_02 = np.arange(1,10).reshape(3,3)
print("The first array\n",array_01)
print("The second array\n",array_02)
arrayAdd = array_01 + array_02
print("\nAddition of two array : ")
print(arrayAdd)

The first array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The second array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Addition of two array : 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [10]:
# add method
np.add(array_01, array_02)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [13]:
# Subtract
np.subtract(array_01, array_02)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
# Division
array_01 / array_02

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# Normal way multiply
array_01 * array_02


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
# multiply function

np.multiply(array_01,array_02)


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [18]:
# Two Matrix Product
print("The first array\n",array_01)
print("The second array\n",array_02)
array_01 @ array_02

The first array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The second array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [19]:
# Two Matrix Product using Dot fuction
print("The first array\n",array_01)
print("The second array\n",array_02)
array_01.dot(array_02)

The first array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The second array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [20]:
# Maximum Function
array_01.max()

9

In [21]:
# index value
array_01.argmax()

8

In [24]:
# Axis value find .max(axis = 0 for coloumn, 1 for row)
array_01.max(axis = 0)

array([7, 8, 9])

In [25]:
array_01.max(axis = 1)

array([3, 6, 9])

In [27]:
# Minimum Value find
array_01.min()

1

In [28]:
array_01.min(axis = 0)

array([1, 2, 3])

In [29]:
array_01.min(axis = 1)

array([1, 4, 7])

In [30]:
# Sum = 2+2 = 4 O/p
np.sum(array_01)

45

In [31]:
# Sum (argument for particular row =0/coulmn= 1)
np.sum(array_01, axis = 0)

array([12, 15, 18])

In [32]:
# Row
np.sum(array_01, axis = 1)

array([ 6, 15, 24])

In [44]:
# Mean of Array
print(array_01)
print("Mean of first Array  :")
np.mean(array_01)
# Square
np.sqrt(array_01)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean of first Array  :


array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [45]:
# Standard Deivision
np.std(array_01)


2.581988897471611

In [46]:
# Expoenent
np.exp(array_01)


array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [47]:
# Log
np.log(array_01)


array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [48]:
# Log base 10
np.log10(array_01)


array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])